### ISSUE TITLE
About Chinese coding problem

### ISSUE THREAD

**Issue by LuanShiZhiJian** [yongfa365/yongfa365-jmeter-plugins#2]
Hello, I have met a Chinese coding problem, please help. thanks.

![image](https://user-images.githubusercontent.com/41558924/148171639-dc825d08-5cc6-4052-8e3e-c0b81803d0a4.png)

How can we solve this problem or need to offer?

**Comment by yongfa365** [comment]
will update: https://github.com/undera/jmeter-plugins/pull/508
